name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 15.x
        uses: actions/setup-node@v3
        with:
          node-version: 15.x
      - run: apt update
      - run: apt -y install postgresql
      - run: |
          cp ci_env .env
          cd ./backend
          npm ci
          npm run build --if-present
          npm start & npx wait-on http://localhost:3000
